services:

  db:

    image: postgres:15

    container_name: kaufeedback-db

    environment:

      POSTGRES_DB: kaufeedback

      POSTGRES_USER: mhcadmin

      POSTGRES_PASSWORD: Nonprod786mhc

    ports:

      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

  backend:

    build:

      context: ./backend

    container_name: kaufeedback-backend

    ports:

      - "8080:8080"

    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://mhc-nonprod-rds.c5wuy6eiozin.ap-south-1.rds.amazonaws.com:5432/kaufeedback

      SPRING_DATASOURCE_USERNAME: mhcadmin

      SPRING_DATASOURCE_PASSWORD: Nonprod786mhc

    depends_on:

      - db

  frontend:

    build:

      context: ./frontend

    container_name: kaufeedback-frontend

    ports:

      - "80:80"

    depends_on:

      - backend

volumes:

  postgres_data:
